name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup target add wasm32-unknown-unknown
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - run: cargo install trunk
    - run: trunk build --release --public-url jovi-jovi
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
